apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
  labels:
    app: ecomm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: 636706114596.dkr.ecr.us-east-1.amazonaws.com/ecomm-repo:v0.1
        ports:
        - containerPort: 8080




